name: Release Go project

on:
  push:
    branches:
      - master

jobs:
  tag:
    permissions: write-all
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
        WITH_V: true
  build:
    permissions: write-all
    needs:
      - tag
    name: GoReleaser build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go 1.20.0
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.0
        id: go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release --clean
          workdir: ./cmd/
        env:
          CGO_ENABLED: 0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}